Derive and publish camera info (#7)
* Update MTC library with pre-release patch
Fixes faults while tracking XPAs on Linux

* Add generated html docs for current MTC library version

* Add OpenCV as depend

* Add enum mtSideI to index image sides

* Stage rough outline

* Add generateObjectPoints helper function

* Sample stereoCalibrate points via grid

* Simplify setting camera info message

* Use frame id param for the moment

* Down sample grid and use mm units

* Simplify

* Down sample grid and increase side sizes

* Set binning for 4:1 decimation for now

* Set initial intrinsic guess

* Increase sampling

* Extend flags for stereoCalibrate

* Tweak criteria?

* Linting

* Add left camera view

* Add left camera info
and change 3D view orientation

* Remove binning from camera info
to avoid distorting rviz camera info polygon edges

* Simplify

* Use separate R and T for each camera

* Calibrate each camera separately
prior to calibrating stereo extrinsic
to try and simplify final convergence

* Revert mono calibration for now
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) ./modules/calib3d/src/calibration.cpp:1575: error: (-5:Bad argument) For non-planar calibration rigs the initial intrinsic matrix must be specified in function 'cvCalibrateCamera2Internal'
```

* Set and check jitter filter for all markers

* printout jitter parameters. Modify TF publisher timestamp
Co-authored-by: Ruffin <roxfoxpox@gmail.com>

* Change diagnostics messages to use RCLCPP_INFO
instead of RCLCPP_WARN

* Revert broadcasted TFs to use common header

* Stamp common header via system clock
instead of relative to hardware clock
to avoid TF lookup syncopation issue

* Revert "Revert mono calibration for now"

This reverts commit 35f8ad80330c6c548da1102fd013e9ecd1b9b669.

* Solve for intrinsics via stereoCalibrate
as two step solving cia calibrateCamera
results in erroneous calibration
given object points are not in right camera reference frame?

* Avoid sigfaults upon node teardown

---------

Co-authored-by: zyu130 <zyu130@gmail.com>